// AUTO-GENERATED by test/fetch_storms.mjs or test/bake_for_ls.mjs.
// Source: GDACS · Global Disaster Alert and Coordination System
// Fetched: 2026-05-31T16:10:47.941Z
// Mode: live

export interface Storm {
  key: string;
  eventId: string;
  episodeId: string;
  name: string;
  alert: string;
  lon: number | null;
  lat: number | null;
  country: string;
  fromDate: string;
  toDate: string;
  severity: number | null;
  severityText: string;
  windKmh: number | null;
  windMps: number | null;
  status: string;
  windBand: string;
  coordinateLabel: string;
  updatedLabel: string;
  url: string;
  summary: string;
}

export const STORMS_SOURCE = "GDACS · Global Disaster Alert and Coordination System";
export const STORMS_SOURCE_URL = "https://www.gdacs.org/";
export const STORMS_FETCHED_AT = "2026-05-31T16:10:47.941Z";
export const STORMS_GENERATED_AT = "2026-05-31T17:29:02.163Z";
export const STORMS_WINDOW_SINCE = "2026-05-17";
export const STORMS_DATA_MODE = "live";
export const STORMS_USING_FALLBACK = false;
export const STORMS_FALLBACK_REASON = "";
export const STORMS: Storm[] = [
  {
    "key": "1001272-18",
    "eventId": "1001272",
    "episodeId": "18",
    "name": "JANGMI-26",
    "alert": "Green",
    "lon": 127.7,
    "lat": 22.8,
    "country": "Japan",
    "fromDate": "2026-05-27T06:00:00",
    "toDate": "2026-05-31T12:00:00",
    "severity": 138.888,
    "severityText": "Hurricane/Typhoon > 74 mph (maximum wind speed of 139 km/h)",
    "windKmh": 138.9,
    "windMps": 38.6,
    "status": "Hurricane/Typhoon > 74 mph",
    "windBand": "Category 1 equivalent",
    "coordinateLabel": "22.8°N, 127.7°E",
    "updatedLabel": "2026-05-31 10:00 UTC",
    "url": "https://www.gdacs.org/report.aspx?eventid=1001272&episodeid=18&eventtype=TC",
    "summary": "JANGMI-26 is reported near Japan. GDACS lists 139 km/h (38.6 m/s) maximum wind and a Green alert level."
  }
];
