// AUTO-GENERATED by tools/update_weather_live.mjs.
// Source: GDACS · Global Disaster Alert and Coordination System
// Fetched: 2026-06-08T08:57:23Z
// Mode: live

export interface Storm {
  key: string;
  eventId: string;
  episodeId: string;
  name: string;
  alert: string;
  lon: number | null;
  lat: number | null;
  country: string;
  fromDate: string;
  toDate: string;
  severity: number | null;
  severityText: string;
  windKmh: number | null;
  windMps: number | null;
  status: string;
  windBand: string;
  coordinateLabel: string;
  updatedLabel: string;
  url: string;
  summary: string;
}

export const STORMS_SOURCE = "GDACS · Global Disaster Alert and Coordination System";
export const STORMS_SOURCE_URL = "https://www.gdacs.org/";
export const STORMS_FETCHED_AT = "2026-06-08T08:57:23Z";
export const STORMS_GENERATED_AT = "2026-06-08T08:57:23Z";
export const STORMS_WINDOW_SINCE = "2026-06-08";
export const STORMS_DATA_MODE = "live";
export const STORMS_USING_FALLBACK = false;
export const STORMS_FALLBACK_REASON = "";
export const STORMS: Storm[] = [
  {
    "key": "1001274-3",
    "eventId": "1001274",
    "episodeId": "3",
    "name": "TWO-E-26",
    "alert": "Green",
    "lon": -99.4,
    "lat": 15.3,
    "country": "Mexico",
    "fromDate": "2026-06-07T15:00:00",
    "toDate": "2026-06-08T03:00:00",
    "severity": 64.8144,
    "severityText": "Tropical Depression (maximum wind speed of 65 km/h)",
    "windKmh": 64.8,
    "windMps": 18,
    "status": "Tropical Depression (maximum wind speed of 65 km/h)",
    "windBand": "tropical storm",
    "coordinateLabel": "15.3°N, 99.4°W",
    "updatedLabel": "2026-06-08 03:00 UTC",
    "url": "https://www.gdacs.org/report.aspx?eventtype=TC&eventid=1001274",
    "summary": "From 07/06/2026 to 08/06/2026, a Tropical Depression (maximum wind speed of 65 km/h) TWO-E-26 was active in Atlantic. The cyclone affects these countries: Mexico (vulnerability Medium). Estimated population affected by category 1 (120 km/h) wind speeds or higher is 0 (0.114 million in tropical storm)."
  },
  {
    "key": "1001273-22",
    "eventId": "1001273",
    "episodeId": "22",
    "name": "AMANDA-26",
    "alert": "Green",
    "lon": -136.3,
    "lat": 11.3,
    "country": "",
    "fromDate": "2026-06-02T21:00:00",
    "toDate": "2026-06-08T03:00:00",
    "severity": 74.0736,
    "severityText": "Tropical Depression (maximum wind speed of 46 km/h)",
    "windKmh": 74.1,
    "windMps": 20.6,
    "status": "Tropical Depression (maximum wind speed of 46 km/h)",
    "windBand": "tropical storm",
    "coordinateLabel": "11.3°N, 136.3°W",
    "updatedLabel": "2026-06-08 03:00 UTC",
    "url": "https://www.gdacs.org/report.aspx?eventtype=TC&eventid=1001273",
    "summary": "From 02/06/2026 to 08/06/2026, a Tropical Depression (maximum wind speed of 74 km/h) AMANDA-26 was active in EastPacific. The cyclone affects these countries: [unknown] (vulnerability [unknown]). Estimated population affected by category 1 (120 km/h) wind speeds or higher is 0 (0 in tropical storm)."
  }
];
