// StoryGuideLayoutGenerated.ts
// Generated by test/render_story_ui.mjs. Edit web/story-ui-layout.mjs instead.

export type StoryGuideSlot = {
    x: number;
    y: number;
    width: number;
    height: number;
};

export type StoryGuideStep = {
    id: string;
    index: string;
    title: string;
    root: string;
    canCalibrate: boolean;
    slot: StoryGuideSlot;
};

export type StoryGuideExample = {
    id: string;
    index: string;
    title: string;
    canCalibrate: boolean;
    slot: StoryGuideSlot;
};

export type StoryGuideTheoryCard = {
    id: string;
    index: string;
    title: string;
    slot: StoryGuideSlot;
};

export type StoryGuideTheoryMode = {
    id: string;
    index: string;
    title: string;
    slot: StoryGuideSlot;
};

export type StoryGuideGradientPalette = {
    id: string;
    index: string;
    title: string;
    slot: StoryGuideSlot;
};

export const STORY_GUIDE_TEXTURE = {
    widthPx: 1500,
    heightPx: 1000,
    widthCm: 30,
    heightCm: 20,
    pixelsPerCm: 50,
};

export const STORY_GUIDE_PANEL = {
    width: 30,
    height: 20,
};

export const STORY_GUIDE_STEPS: StoryGuideStep[] = [
    {
        "id": "theory",
        "index": "01",
        "title": "Theory",
        "root": "C02_Theory",
        "canCalibrate": false,
        "slot": {
            "x": -6.8,
            "y": -1.9,
            "width": 12.8,
            "height": 13
        }
    },
    {
        "id": "examples",
        "index": "02",
        "title": "Real World",
        "root": "C03_Real_World_Examples",
        "canCalibrate": true,
        "slot": {
            "x": 6.8,
            "y": -1.9,
            "width": 12.8,
            "height": 13
        }
    }
];

export const STORY_GUIDE_THEORY_CARDS = [
    {
        "id": "definition",
        "index": "01",
        "title": "Definition",
        "slot": {
            "x": -9.6,
            "y": -1.64,
            "width": 8,
            "height": 12
        }
    },
    {
        "id": "metrics",
        "index": "02",
        "title": "Field Metrics",
        "slot": {
            "x": 0,
            "y": -1.64,
            "width": 8,
            "height": 12
        }
    },
    {
        "id": "patterns",
        "index": "03",
        "title": "Analytical Examples",
        "slot": {
            "x": 9.6,
            "y": -1.64,
            "width": 8,
            "height": 12
        }
    }
] as StoryGuideTheoryCard[];

export const STORY_GUIDE_EXAMPLES = {
    back: {"x":-11.2,"y":7.76,"width":4.8,"height":1.68},
    cards: [
    {
        "id": "gravity",
        "index": "01",
        "title": "Gravitational Fields",
        "canCalibrate": true,
        "slot": {
            "x": 0,
            "y": 3.12,
            "width": 27.2,
            "height": 2.8
        }
    },
    {
        "id": "magnetism",
        "index": "02",
        "title": "Magnetism",
        "canCalibrate": true,
        "slot": {
            "x": 0,
            "y": -0.08,
            "width": 27.2,
            "height": 2.8
        }
    },
    {
        "id": "wind",
        "index": "03",
        "title": "Earth Winds",
        "canCalibrate": true,
        "slot": {
            "x": 0,
            "y": -3.28,
            "width": 27.2,
            "height": 2.8
        }
    },
    {
        "id": "aerodynamics",
        "index": "04",
        "title": "Aerodynamics",
        "canCalibrate": true,
        "slot": {
            "x": 0,
            "y": -6.48,
            "width": 27.2,
            "height": 2.8
        }
    }
] as StoryGuideExample[],
};

export const STORY_GUIDE_EXAMPLE_DETAIL = {
    info: {"x":0,"y":2.06,"width":26.4,"height":4.2},
    modes: [
    {
        "x": -9.2,
        "y": -4.42,
        "width": 8,
        "height": 1.64
    },
    {
        "x": 0,
        "y": -4.42,
        "width": 8,
        "height": 1.64
    },
    {
        "x": 9.2,
        "y": -4.42,
        "width": 8,
        "height": 1.64
    }
] as StoryGuideSlot[],
    magneticModes: [
    {
        "x": -4.6,
        "y": -4.42,
        "width": 8,
        "height": 1.64
    },
    {
        "x": 4.6,
        "y": -4.42,
        "width": 8,
        "height": 1.64
    }
] as StoryGuideSlot[],
};

export const STORY_GUIDE_THEORY = {
    info: {"x":-9.04,"y":-2.4,"width":8.88,"height":6.72},
    modes: [
    {
        "id": "expansion",
        "index": "01",
        "title": "Expansion",
        "slot": {
            "x": -9.1,
            "y": 3,
            "width": 5,
            "height": 1.52
        }
    },
    {
        "id": "contraction",
        "index": "02",
        "title": "Contraction",
        "slot": {
            "x": -3.1,
            "y": 3,
            "width": 5,
            "height": 1.52
        }
    },
    {
        "id": "curl",
        "index": "03",
        "title": "Curl",
        "slot": {
            "x": 2.9,
            "y": 3,
            "width": 5,
            "height": 1.52
        }
    },
    {
        "id": "motion",
        "index": "04",
        "title": "Motion",
        "slot": {
            "x": 8.9,
            "y": 3,
            "width": 5,
            "height": 1.52
        }
    }
] as StoryGuideTheoryMode[],
};

export const STORY_GUIDE_GRADIENTS = {
    palettes: [
    {
        "id": "jet",
        "index": "01",
        "title": "Jet",
        "slot": {
            "x": 0.22,
            "y": 0,
            "width": 6.28,
            "height": 1.6
        }
    },
    {
        "id": "viridis",
        "index": "02",
        "title": "Viridis",
        "slot": {
            "x": 7.1,
            "y": 0,
            "width": 6.28,
            "height": 1.6
        }
    },
    {
        "id": "plasma",
        "index": "03",
        "title": "Plasma",
        "slot": {
            "x": 0.22,
            "y": -2.08,
            "width": 6.28,
            "height": 1.6
        }
    }
] as StoryGuideGradientPalette[],
};

export const STORY_GUIDE_NAV = {
    back: {"x":-11,"y":-7.44,"width":5.2,"height":2.24},
    next: {"x":11,"y":-7.44,"width":5.2,"height":2.24},
    progress: {"x":0,"y":-7.44,"width":14.4,"height":2.24},
};

export const STORY_GUIDE_UTILITY = {
    follow: {"x":5.6,"y":8.46,"width":5.2,"height":1.72},
    fold: {"x":11.6,"y":8.46,"width":5.2,"height":1.72},
    planeFloor: {"x":5.6,"y":6.38,"width":5.2,"height":1.72},
    planeFront: {"x":11.6,"y":6.38,"width":5.2,"height":1.72},
};

export const STORY_GUIDE_VARIANTS = {
    primary: {"x":-9.2,"y":-1.86,"width":8,"height":1.64},
    secondary: {"x":0,"y":-1.86,"width":8,"height":1.64},
    artemis: {"x":0,"y":-3.16,"width":26.4,"height":5.36},
};
