#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = new URL("..", import.meta.url).pathname;
const GFS_URL = "https://upwell.pfeg.noaa.gov/erddap/griddap/ncep_global_lon180";
const GDACS_RSS_URL = "https://www.gdacs.org/xml/rss.xml";
const GFS_SOURCE = "NOAA ERDDAP · ncep_global_lon180 (NCEP GFS Atmospheric Model)";
const GFS_SOURCE_URL = "https://upwell.pfeg.noaa.gov/erddap/griddap/ncep_global_lon180.html";
const NX = 180;
const NY = 91;
const LON_MIN = -180;
const LON_MAX = 178;
const LAT_MAX = 90;
const LAT_MIN = -90;
const LON_RES = 2;
const LAT_RES = 2;
const STEP_HOURS = 3;
const QUANT_SCALE = 100;

function isoNoMs(date) {
  return date.toISOString().replace(/\.\d{3}Z$/, "Z");
}

function nearestGfsTime(now = new Date()) {
  const stepMs = STEP_HOURS * 3600 * 1000;
  return new Date(Math.round(now.getTime() / stepMs) * stepMs);
}

function encodeErddapTime(iso) {
  return encodeURIComponent(`(${iso})`);
}

async function fetchText(url) {
  const response = await fetch(url, {
    headers: {
      "User-Agent": "VectorFieldsWeatherUpdater/1.0",
    },
  });
  if (!response.ok) {
    throw new Error(`${response.status} ${response.statusText}: ${url}`);
  }
  return await response.text();
}

function csvEscape(value) {
  if (value.indexOf(",") < 0 && value.indexOf('"') < 0 && value.indexOf("\n") < 0) return value;
  return `"${value.replace(/"/g, '""')}"`;
}

function parseCsv(text) {
  const rows = [];
  let row = [];
  let value = "";
  let quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"' && text[i + 1] === '"') {
        value += '"';
        i++;
      } else if (c === '"') {
        quoted = false;
      } else {
        value += c;
      }
    } else if (c === '"') {
      quoted = true;
    } else if (c === ",") {
      row.push(value);
      value = "";
    } else if (c === "\n") {
      row.push(value.replace(/\r$/, ""));
      rows.push(row);
      row = [];
      value = "";
    } else {
      value += c;
    }
  }
  if (value.length > 0 || row.length > 0) {
    row.push(value);
    rows.push(row);
  }
  return rows;
}

async function fetchGfsSlice(targetIso) {
  const t = encodeErddapTime(targetIso);
  const query = `ugrd10m%5B${t}%5D%5B0:4:360%5D%5B0:4:716%5D,vgrd10m%5B${t}%5D%5B0:4:360%5D%5B0:4:716%5D`;
  const url = `${GFS_URL}.csv?${query}`;
  const text = await fetchText(url);
  const rows = parseCsv(text).filter((row) => row.length >= 5);
  const header = rows[0] || [];
  if (header[0] !== "time" || header[3] !== "ugrd10m" || header[4] !== "vgrd10m") {
    throw new Error(`Unexpected GFS CSV header: ${header.map(csvEscape).join(",")}`);
  }

  const dataRows = rows.slice(2);
  const expected = NX * NY;
  if (dataRows.length !== expected) {
    throw new Error(`Expected ${expected} GFS rows, got ${dataRows.length}`);
  }

  const u = new Array(expected);
  const v = new Array(expected);
  for (let i = 0; i < dataRows.length; i++) {
    const row = dataRows[i];
    u[i] = Math.round(Number(row[3]) * QUANT_SCALE);
    v[i] = Math.round(Number(row[4]) * QUANT_SCALE);
  }
  return { u, v };
}

function formatNumberArray(values, perLine = 24) {
  const lines = [];
  for (let i = 0; i < values.length; i += perLine) {
    lines.push("  " + values.slice(i, i + perLine).join(", "));
  }
  return lines.join(",\n");
}

function gfsFile({ targetIso, fetchedAt, u, v }) {
  const meta = {
    source: GFS_SOURCE,
    sourceUrl: GFS_SOURCE_URL,
    datasetId: "ncep_global_lon180",
    variable: "10 m wind (ugrd10m, vgrd10m)",
    refTime: targetIso,
    endTime: targetIso,
    stepHours: STEP_HOURS,
    nt: 1,
    ny: NY,
    nx: NX,
    lonMin: LON_MIN,
    lonMax: LON_MAX,
    latMax: LAT_MAX,
    latMin: LAT_MIN,
    lonRes: LON_RES,
    latRes: LAT_RES,
    times: [targetIso],
    units: "m/s",
    layout: "Int16 centi-m/s arrays baked for Lens Studio, [u, v] for one selected timestep",
    fetchedAt,
    lastAttemptAt: fetchedAt,
    dataMode: "live",
    usingFallback: false,
    fallbackReason: "",
    nullCount: 0,
    attemptedSources: [
      {
        sourceUrl: GFS_SOURCE_URL,
        targetIso,
        ok: true,
      },
    ],
    bakedFromWindow: {
      refTime: targetIso,
      endTime: targetIso,
      times: [targetIso],
      selectedIndex: 0,
    },
  };

  return `// AUTO-GENERATED by tools/update_weather_live.mjs - do not edit by hand.
// Source: ${GFS_SOURCE}
// Baked live-nearest timestep: ${targetIso}
// Grid:   ${NX} lon x ${NY} lat at ${LON_RES}° / ${LAT_RES}°

export const GFS_META = ${JSON.stringify(meta, null, 2)};

const GFS_QUANT_SCALE = ${QUANT_SCALE};
const GFS_U_I16: number[] = [
${formatNumberArray(u)}
];
const GFS_V_I16: number[] = [
${formatNumberArray(v)}
];

export function loadGfsArrays(): { u: Float32Array; v: Float32Array } {
  const total = GFS_META.nt * GFS_META.ny * GFS_META.nx;
  const u = new Float32Array(total);
  const v = new Float32Array(total);
  for (let i = 0; i < total; i++) {
    u[i] = GFS_U_I16[i] / GFS_QUANT_SCALE;
    v[i] = GFS_V_I16[i] / GFS_QUANT_SCALE;
  }
  return { u, v };
}
`;
}

function tag(text, name) {
  const match = text.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`, "i"));
  return match ? decodeXml(match[1].trim()) : "";
}

function attr(text, name) {
  const match = text.match(new RegExp(`${name}="([^"]*)"`, "i"));
  return match ? decodeXml(match[1]) : "";
}

function decodeXml(value) {
  return value
    .replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, "$1")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'");
}

function stripHtml(value) {
  return value.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
}

function numberOrNull(value) {
  if (!value || value.length === 0) return null;
  const n = Number(value);
  return Number.isFinite(n) ? n : null;
}

function parseRssDate(value) {
  if (!value) return "";
  const d = new Date(value);
  return Number.isFinite(d.getTime()) ? d.toISOString().replace(/\.\d{3}Z$/, "") : value;
}

function extractStorms(rss) {
  const items = [...rss.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map((m) => m[1]);
  const storms = [];
  for (const item of items) {
    const eventType = tag(item, "gdacs:eventtype");
    if (eventType !== "TC") continue;
    const eventId = tag(item, "gdacs:eventid");
    const episodeId = tag(item, "gdacs:episodeid");
    const alert = tag(item, "gdacs:alertlevel") || tag(item, "gdacs:episodealertlevel") || "";
    const lat = numberOrNull(tag(item, "geo:lat"));
    const lon = numberOrNull(tag(item, "geo:long"));
    const country = tag(item, "gdacs:country");
    const severityTag = item.match(/<gdacs:severity\b([^>]*)>([\s\S]*?)<\/gdacs:severity>/i);
    const severity = severityTag ? numberOrNull(attr(severityTag[1], "value")) : null;
    const severityText = severityTag ? stripHtml(decodeXml(severityTag[2].trim())) : "";
    const windKmh = severity !== null && severity > 0 ? Math.round(severity * 10) / 10 : null;
    const windMps = windKmh !== null ? Math.round((windKmh / 3.6) * 10) / 10 : null;
    const title = tag(item, "title");
    const eventName = tag(item, "gdacs:eventname");
    const name = eventName || title.replace(/^(Green|Orange|Red)\s+/i, "").replace(/\s+alert.*$/i, "").trim() || "Tracked cyclone";
    const fromDate = parseRssDate(tag(item, "gdacs:fromdate"));
    const toDate = parseRssDate(tag(item, "gdacs:todate") || tag(item, "gdacs:datemodified") || tag(item, "pubDate"));
    const updatedLabel = toDate ? toDate.replace("T", " ").replace(/:00Z?$/, " UTC") : "";
    const coordinateLabel = lat !== null && lon !== null ? `${Math.abs(lat).toFixed(1)}°${lat >= 0 ? "N" : "S"}, ${Math.abs(lon).toFixed(1)}°${lon >= 0 ? "E" : "W"}` : "";
    const windBand = windKmh === null
      ? "wind pending"
      : windKmh >= 252 ? "Category 5 equivalent"
      : windKmh >= 209 ? "Category 4 equivalent"
      : windKmh >= 178 ? "Category 3 equivalent"
      : windKmh >= 154 ? "Category 2 equivalent"
      : windKmh >= 119 ? "Category 1 equivalent"
      : "tropical storm";
    storms.push({
      key: `${eventId}-${episodeId}`,
      eventId,
      episodeId,
      name,
      alert,
      lon,
      lat,
      country,
      fromDate,
      toDate,
      severity,
      severityText,
      windKmh,
      windMps,
      status: severityText || title,
      windBand,
      coordinateLabel,
      updatedLabel,
      url: tag(item, "link"),
      summary: stripHtml(tag(item, "description")),
    });
  }
  return storms.slice(0, 8);
}

function stormsFile({ rss, fetchedAt }) {
  const channelPubDate = parseRssDate(tag(rss, "pubDate"));
  const storms = extractStorms(rss);
  return `// AUTO-GENERATED by tools/update_weather_live.mjs.
// Source: GDACS · Global Disaster Alert and Coordination System
// Fetched: ${fetchedAt}
// Mode: live

export interface Storm {
  key: string;
  eventId: string;
  episodeId: string;
  name: string;
  alert: string;
  lon: number | null;
  lat: number | null;
  country: string;
  fromDate: string;
  toDate: string;
  severity: number | null;
  severityText: string;
  windKmh: number | null;
  windMps: number | null;
  status: string;
  windBand: string;
  coordinateLabel: string;
  updatedLabel: string;
  url: string;
  summary: string;
}

export const STORMS_SOURCE = "GDACS · Global Disaster Alert and Coordination System";
export const STORMS_SOURCE_URL = "https://www.gdacs.org/";
export const STORMS_FETCHED_AT = "${fetchedAt}";
export const STORMS_GENERATED_AT = "${fetchedAt}";
export const STORMS_WINDOW_SINCE = "${channelPubDate ? channelPubDate.slice(0, 10) : fetchedAt.slice(0, 10)}";
export const STORMS_DATA_MODE = "live";
export const STORMS_USING_FALLBACK = false;
export const STORMS_FALLBACK_REASON = "";
export const STORMS: Storm[] = ${JSON.stringify(storms, null, 2)};
`;
}

async function main() {
  const fetchedAt = isoNoMs(new Date());
  const targetIso = isoNoMs(nearestGfsTime(new Date()));
  console.log(`Fetching GFS ${targetIso}`);
  const gfs = await fetchGfsSlice(targetIso);
  console.log(`Fetching GDACS RSS`);
  const rss = await fetchText(GDACS_RSS_URL);
  await writeFile(join(ROOT, "Assets/Scripts/GfsData.ts"), gfsFile({ targetIso, fetchedAt, ...gfs }));
  await writeFile(join(ROOT, "Assets/Scripts/StormsData.ts"), stormsFile({ rss, fetchedAt }));
  console.log(`Updated GfsData.ts and StormsData.ts at ${fetchedAt}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
